#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Compare embeddings: precomputed vs generated by pipeline
"""

import sys
sys.path.insert(0, '/home/prerna/LIMU-BERT-blind-users')

import numpy as np
import torch
from inference_exact import ExactSonyWatchPipeline

def main():
    print("="*80)
    print("Comparing Embeddings: Precomputed vs Pipeline")
    print("="*80)
    
    # Paths
    embedder_path = "/home/prerna/LIMU-BERT-blind-users/saved/pretrain_base_sony_watch_20_120/limu_v1.pt"
    classifier_path = "/home/prerna/LIMU-BERT-blind-users/saved/classifier_contrastive_gru_sony_watch_20_120/limu_gru_v1.pt"
    data_path = "/home/prerna/LIMU-BERT-blind-users/dataset/sony_watch/data_20_120.npy"
    precomputed_embed_path = "/home/prerna/LIMU-BERT-blind-users/embed/embed_limu_v1_sony_watch_20_120.npy"
    
    # Load data
    print("\nLoading data...")
    data = np.load(data_path)
    precomputed_embeds = np.load(precomputed_embed_path)
    print(f"Data shape: {data.shape}")
    print(f"Precomputed embeddings shape: {precomputed_embeds.shape}")
    
    # Initialize pipeline
    print("\nInitializing pipeline...")
    pipeline = ExactSonyWatchPipeline(
        embedder_path=embedder_path,
        classifier_path=classifier_path
    )
    
    # Test on a few samples
    print("\n" + "="*80)
    print("Testing 5 samples")
    print("="*80)
    
    test_indices = [0, 100, 500, 1000, 2000]
    
    for idx in test_indices:
        raw_data = data[idx]
        
        # Get embedding from pipeline
        data_tensor, nucleus_mask, sig_axis_mask, metadata = pipeline.preprocess(raw_data)
        
        with torch.no_grad():
            pipeline_embed = pipeline.embedder(
                data_tensor,
                masked_pos=None,
                nucleus_mask=nucleus_mask,
                sig_axis_mask=sig_axis_mask
            )
        
        pipeline_embed_np = pipeline_embed.cpu().numpy()[0]  # (120, 72)
        precomputed_embed_np = precomputed_embeds[idx]  # (120, 72)
        
        # Compare
        diff = np.abs(pipeline_embed_np - precomputed_embed_np)
        max_diff = np.max(diff)
        mean_diff = np.mean(diff)
        
        print(f"\nSample {idx}:")
        print(f"  Pipeline embed shape: {pipeline_embed_np.shape}")
        print(f"  Precomputed embed shape: {precomputed_embed_np.shape}")
        print(f"  Max difference: {max_diff:.6f}")
        print(f"  Mean difference: {mean_diff:.6f}")
        print(f"  Pipeline embed [0,:5]: {pipeline_embed_np[0,:5]}")
        print(f"  Precomputed embed [0,:5]: {precomputed_embed_np[0,:5]}")
        
        if max_diff < 1e-4:
            print(f"  ✓ Embeddings match!")
        else:
            print(f"  ✗ Embeddings differ significantly!")

if __name__ == "__main__":
    main()
